#!/usr/bin/env python3
"""Render one approved shot-local virtual-camera event with sub-pixel sampling.

This helper intentionally renders a single continuous-shot event. It never
spans cuts, never follows a face tracker, and never infers emphasis. The input
plan is generated by ``plan_virtual_camera.py`` and the output is a silent
source-backed intermediate under the same approved edit directory.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from asset_gate import canonical_edit_dir, path_under_edit, require_asset_gate
from visual_asset_provenance import (
    FileSnapshot,
    VisualProvenanceError,
    assert_snapshots_current,
    build_virtual_camera_provenance,
    capture_virtual_camera_renderer_snapshots,
    load_approved_visual_plan_item,
    provenance_path_for,
    verify_visual_asset_provenance,
)


VERSION = "sprut-virtual-camera-render-1"


class CameraRenderError(RuntimeError):
    pass


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def probe_video(path: Path) -> dict[str, Any]:
    ffprobe = shutil.which("ffprobe")
    if not ffprobe:
        raise CameraRenderError("ffprobe is unavailable")
    result = subprocess.run(
        [ffprobe, "-v", "error", "-select_streams", "v:0", "-show_entries",
         "stream=width,height,avg_frame_rate:format=duration", "-of", "json", str(path)],
        text=True, capture_output=True, check=False,
    )
    if result.returncode:
        raise CameraRenderError(result.stderr.strip())
    value = json.loads(result.stdout)
    stream = value["streams"][0]
    numerator, denominator = (int(part) for part in stream["avg_frame_rate"].split("/"))
    return {
        "width": int(stream["width"]), "height": int(stream["height"]),
        "fps": numerator / denominator, "duration_s": float(value["format"]["duration"]),
    }


def interpolate(keyframes: list[dict[str, Any]], time_s: float, key: str) -> float:
    if time_s <= float(keyframes[0]["time_s"]):
        return float(keyframes[0][key])
    for left, right in zip(keyframes, keyframes[1:]):
        a, b = float(left["time_s"]), float(right["time_s"])
        if time_s <= b + 1e-9:
            amount = 0.0 if b <= a else (time_s - a) / (b - a)
            return float(left[key]) + (float(right[key]) - float(left[key])) * amount
    return float(keyframes[-1][key])


def render_frame_count(event_start: float, event_end: float, fps: float) -> int:
    """Return the exact CFR frame count for the half-open rendered interval."""
    return max(2, round((event_end - event_start) * fps))


def camera_sample_time(index: int, frames: int, event_start: float, event_end: float) -> float:
    """Map first/last output frames to exact reset endpoints without adding a frame."""
    if frames < 2 or index < 0 or index >= frames:
        raise CameraRenderError("camera sample index is outside the rendered frame interval")
    return event_start + (event_end - event_start) * index / (frames - 1)


def render_frames(
    source: Path,
    output: Path,
    keyframes: list[dict[str, Any]],
    event_start: float,
    event_end: float,
    fps: float,
    width: int,
    height: int,
) -> int:
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise CameraRenderError("ffmpeg is unavailable")
    frames = render_frame_count(event_start, event_end, fps)
    command = [
        ffmpeg, "-hide_banner", "-loglevel", "error", "-ss", f"{event_start:.9f}",
        "-i", str(source), "-an", "-vf", f"fps={fps:.12f},format=rgb24",
        "-frames:v", str(frames), "-f", "rawvideo", "pipe:1",
    ]
    decode = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    assert decode.stdout is not None
    encode_command = [
        ffmpeg, "-hide_banner", "-loglevel", "error", "-y", "-f", "rawvideo",
        "-pixel_format", "rgb24", "-video_size", f"{width}x{height}",
        "-framerate", f"{fps:.12f}", "-i", "pipe:0", "-an", "-c:v", "prores_ks",
        "-profile:v", "3", "-pix_fmt", "yuv422p10le", str(output),
    ]
    encode = subprocess.Popen(encode_command, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
    assert encode.stdin is not None
    try:
        import cv2
        import numpy as np
    except ImportError as exc:
        decode.kill(); encode.kill()
        raise CameraRenderError("render_virtual_camera must run in the isolated creative-python runtime") from exc
    frame_bytes = width * height * 3
    written = 0
    try:
        for index in range(frames):
            payload = decode.stdout.read(frame_bytes)
            if len(payload) != frame_bytes:
                break
            frame = np.frombuffer(payload, dtype=np.uint8).reshape(height, width, 3)
            local_time = camera_sample_time(index, frames, event_start, event_end)
            zoom = interpolate(keyframes, local_time, "zoom")
            center_x = interpolate(keyframes, local_time, "center_x") * width
            center_y = interpolate(keyframes, local_time, "center_y") * height
            matrix = np.array(
                [[zoom, 0.0, width / 2.0 - zoom * center_x],
                 [0.0, zoom, height / 2.0 - zoom * center_y]],
                dtype=np.float32,
            )
            transformed = cv2.warpAffine(
                frame, matrix, (width, height), flags=cv2.INTER_LANCZOS4,
                borderMode=cv2.BORDER_REPLICATE,
            )
            encode.stdin.write(transformed.tobytes())
            written += 1
    finally:
        encode.stdin.close()
    decode_stderr = (decode.stderr.read() if decode.stderr else b"").decode("utf-8", "replace")
    encode_stderr = (encode.stderr.read() if encode.stderr else b"").decode("utf-8", "replace")
    decode.wait(); encode.wait()
    if decode.returncode or encode.returncode or written != frames:
        raise CameraRenderError(
            f"camera render failed: decoded={written}/{frames}; decode={decode_stderr}; encode={encode_stderr}"
        )
    return written


def atomic_json(path: Path, value: dict[str, Any]) -> None:
    fd, name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n"); handle.flush(); os.fsync(handle.fileno())
        Path(name).replace(path)
    except Exception:
        Path(name).unlink(missing_ok=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description="Render one approved shot-local virtual-camera event")
    parser.add_argument("--edit-dir", required=True, type=Path)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--plan", required=True, type=Path)
    parser.add_argument("--event-id", required=True)
    parser.add_argument("--visual-id", required=True)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    edit_dir = canonical_edit_dir(args.edit_dir)
    source = path_under_edit(edit_dir, args.source, "camera source")
    plan_path = path_under_edit(edit_dir, args.plan, "camera plan")
    output = path_under_edit(edit_dir, args.output, "camera output")
    if not source.is_file() or source.is_symlink() or not plan_path.is_file() or plan_path.is_symlink():
        raise CameraRenderError("source and plan must be regular local files under edit/")
    sidecar = provenance_path_for(output)
    if output.exists() or sidecar.exists():
        raise CameraRenderError("output or provenance already exists and was left untouched")
    require_asset_gate(edit_dir)
    approved = load_approved_visual_plan_item(edit_dir, args.visual_id)
    if approved.approved_text is not None:
        raise CameraRenderError(
            "virtual-camera visual must have approved_text=null; author text separately"
        )
    source_snapshot = FileSnapshot(source, sha256(source))
    plan_snapshot = FileSnapshot(plan_path, sha256(plan_path))
    renderer_snapshot, helper_snapshot = capture_virtual_camera_renderer_snapshots()
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    if plan.get("type") != "sprut_virtual_camera_plan" or plan.get("generator") != "sprut-virtual-camera-plan-1":
        raise CameraRenderError("plan is not a canonical SPRUT virtual-camera plan")
    events = [item for item in plan.get("events", []) if item.get("id") == args.event_id]
    if len(events) != 1:
        raise CameraRenderError("event-id must identify exactly one plan event")
    event = events[0]
    keyframes = [item for item in plan.get("keyframes", []) if item.get("event_id") == args.event_id]
    if not keyframes or keyframes[0].get("zoom") != 1.0 or keyframes[-1].get("zoom") != 1.0:
        raise CameraRenderError("event keyframes must return exactly to base")
    media = probe_video(source)
    fps = float(plan["fps"])
    if abs(media["fps"] - fps) > 0.01:
        raise CameraRenderError("source must be normalized to the plan CFR before camera rendering")
    start, end = float(event["start_s"]), float(event["end_s"])
    if start < 0 or end > media["duration_s"] + 0.05:
        raise CameraRenderError("camera event falls outside the approved source-backed clip")
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.{os.getpid()}.part.mov")
    try:
        frames = render_frames(source, temporary, keyframes, start, end, fps, media["width"], media["height"])
        require_asset_gate(edit_dir)
        assert_snapshots_current(
            [
                approved.plan_snapshot,
                approved.approval_snapshot,
                source_snapshot,
                plan_snapshot,
                renderer_snapshot,
                helper_snapshot,
            ]
        )
        temporary.replace(output)
        try:
            provenance = build_virtual_camera_provenance(
                edit_dir=edit_dir,
                output=output,
                source_snapshot=source_snapshot,
                plan_snapshot=plan_snapshot,
                approved=approved,
                renderer_snapshot=renderer_snapshot,
                helper_snapshot=helper_snapshot,
                event=event,
                fps=fps,
                frames=frames,
                render_contract=plan["render_contract"],
            )
            atomic_json(sidecar, provenance)
            verify_visual_asset_provenance(
                edit_dir, sidecar, asset_path=output
            )
        except Exception:
            sidecar.unlink(missing_ok=True)
            output.unlink(missing_ok=True)
            raise
    finally:
        temporary.unlink(missing_ok=True)
    print(output)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (
        CameraRenderError,
        VisualProvenanceError,
        OSError,
        ValueError,
        json.JSONDecodeError,
    ) as exc:
        print(f"render_virtual_camera: error: {exc}", file=sys.stderr)
        raise SystemExit(2)
